#!/bin/sh -e

cd mac
rm -rf "build/Release Binary"
rm -rf "build/Release Decimal"
xcodebuild -project Plus42.xcodeproj -target Plus42 -configuration "Release Binary" build
xcodebuild -project Plus42.xcodeproj -target Plus42 -configuration "Release Decimal" build
mkdir tmp
mv "build/Release Binary/Plus42.app" "tmp/Plus42 Binary.app"
mv "build/Release Decimal/Plus42.app" "tmp/Plus42 Decimal.app"
cp README.txt tmp
cd tmp
zip -r ../../Plus42Mac.zip "Plus42 Binary.app" "Plus42 Decimal.app" README.txt
cd ..
rm -rf tmp
cd ..
